export default function About() {
    return <>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quis corporis vero ea aut voluptatum itaque nam neque pariatur, et quas hic, harum sint deserunt ipsam, veniam fuga necessitatibus ipsa! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit beatae quisquam ut impedit, dolore repellat maxime exercitationem eveniet totam omnis unde iusto quis in iste consequuntur voluptatem, placeat soluta rerum. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis cupiditate voluptatum aspernatur praesentium libero, nemo et, fugiat sed ipsam alias ut consectetur cum enim doloribus molestias vel culpa eligendi cumque.</p>
    </>
}